M48
; DRILL file {KiCad 8.0.2} date 2025-01-07T16:45:07-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-07T16:45:07-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0402
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X2.23Y-1.455
X2.23Y-1.605
T2
X0.9449Y-0.944
X0.9449Y-1.811
X2.3622Y-0.944
X2.3622Y-1.811
M30
